### PR TITLE
Made the website responsive

### PR DESCRIPTION
**Pull request by varshilshah-2002**
Made the website responsive and look better. Below I have attached the screenshot of the work. I hope you like the change and accept my pull request.
Thank you 
image

### CODE REVIEW

**Comment by AmreshSinha** [comment]
If buttons can be made better then it would be great :+1:

**Comment by varshilshah-2002** [comment]
I tried a lot but their is some issue with the code so i didnt change
that.Anyways let me try.

**Comment by varshilshah-2002** [comment]
> If buttons can be made better then it would be great 👍

**Comment by varshilshah-2002** [comment]
I have styled the button better when compared to last one.

**Comment by varshilshah-2002** [comment]
I have made the changes.

**Review by surajshende247 — APPROVED** [review]
Good Work 🏆
Buttons are responsive now. I am merging this pull request.

**Pull request merged**
